version: "3.8"

services:
  tracker-dev:
    container_name: tracker-dev
    image: ghcr.io/litestack-hq/lgst-tracker:latest
    restart: unless-stopped
    networks:
      - dev-network
    environment:
      APP_NAME: lgst-tracker-dev
      APP_ENV: development
      APP_KEY: secret
      PORT: 5000
    labels:
      - traefik.enable=true
      - traefik.http.services.tracker_dev.loadbalancer.server.port=5000
      - traefik.http.services.tracker_dev_tcp.loadbalancer.server.port=7000

      - traefik.http.routers.tracker_dev_web.entryPoints=web
      - traefik.http.routers.tracker_dev_web.service=tracker_dev
      - traefik.http.routers.tracker_dev_web.rule=HostRegexp(`{subdomain:([a-z]+\.+)?}dev.wemoov.io`) && PathPrefix(`/api/*/tracker`)
      - traefik.http.routers.tracker_dev_web.priority=3
      - traefik.http.routers.tracker_dev_web.middlewares=https_redirection
      - traefik.http.middlewares.https_redirection.redirectscheme.scheme=https

      - traefik.http.routers.tracker_dev_websecure.entryPoints=websecure
      - traefik.http.routers.tracker_dev_websecure.service=tracker_dev
      - traefik.http.routers.tracker_dev_websecure.tls=true
      - traefik.http.routers.tracker_dev_websecure.rule=HostRegexp(`{subdomain:([a-z]+\.+)?}dev.wemoov.io`) && PathPrefix(`/api/*/tracker`)
      - traefik.http.routers.tracker_dev_websecure.priority=3

      - traefik.http.routers.tracker_dev_tcp.entryPoints=tracker
      - traefik.http.routers.tracker_dev_tcp.rule=Host(`t.dev.wemoov.io`)
      - traefik.http.routers.tracker_dev_tcp.priority=3
      - traefik.http.routers.tracker_dev_tcp.service=tracker_dev_tcp
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async: "true"
        tag: tracker-dev
networks:
  dev-network:
    name: lgst-network-dev