version: "3.8"

services:
  tracker-dev:
    container_name: tracker-dev
    image: ghcr.io/litestack-hq/lgst-tracker:latest
    restart: unless-stopped
    networks:
      - dev-network
    environment:
      APP_NAME: lgst-tracker-dev
      APP_ENV: development
      APP_KEY: secret
      PORT: 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.tracker_dev_secure.entryPoints=websecure
      - traefik.http.routers.tracker_dev_secure.rule=Host(`tracker.dev.wemoov.io`)
      - traefik.http.routers.tracker_dev_secure.priority=3
      - traefik.http.routers.tracker_dev_secure.tls=true
      - traefik.http.routers.tracker_dev_insecure.entryPoints=web
      - traefik.http.routers.tracker_dev_insecure.rule=Host(`tracker.dev.wemoov.io`)
      - traefik.http.routers.tracker_dev_insecure.priority=3
      - traefik.http.routers.tracker_dev_insecure.middlewares=https_redirection
      - traefik.http.middlewares.https_redirection.redirectscheme.scheme=https
      - traefik.http.services.tracker_dev.loadbalancer.server.port=5000
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async: "true"
        tag: tracker-dev
networks:
  dev-network:
    name: lgst-network-dev